// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZusmBL1zN_ZrQknJ7aj7dk_x7jPzrTQ',
    appId: '1:568503198472:web:00dd1db9e9933544c202bd',
    messagingSenderId: '568503198472',
    projectId: 'kickfix-4556a',
    authDomain: 'kickfix-4556a.firebaseapp.com',
    storageBucket: 'kickfix-4556a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65b_kwpku8DbNhPmvwXhNeNxI1VYljfI',
    appId: '1:568503198472:android:93426f8c0abb19c6c202bd',
    messagingSenderId: '568503198472',
    projectId: 'kickfix-4556a',
    storageBucket: 'kickfix-4556a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA2Hmybia2waqDumaXy4SLuLnFn0hQ96o',
    appId: '1:568503198472:ios:1059b95ea00c078ec202bd',
    messagingSenderId: '568503198472',
    projectId: 'kickfix-4556a',
    storageBucket: 'kickfix-4556a.appspot.com',
    iosBundleId: 'com.example.kickFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA2Hmybia2waqDumaXy4SLuLnFn0hQ96o',
    appId: '1:568503198472:ios:1059b95ea00c078ec202bd',
    messagingSenderId: '568503198472',
    projectId: 'kickfix-4556a',
    storageBucket: 'kickfix-4556a.appspot.com',
    iosBundleId: 'com.example.kickFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZusmBL1zN_ZrQknJ7aj7dk_x7jPzrTQ',
    appId: '1:568503198472:web:837d014f3d3a2cd5c202bd',
    messagingSenderId: '568503198472',
    projectId: 'kickfix-4556a',
    authDomain: 'kickfix-4556a.firebaseapp.com',
    storageBucket: 'kickfix-4556a.appspot.com',
  );
}
